name: Deploy site to Cloudflare Page

on:
  push:
    branches: [main, preview]

jobs:
  build:
    runs-on: ubuntu-22.04:host
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - name: Deploy to Local hosting
        run: ls -Al && ls -Al .. && ls -Al ../.. && ls -Al ../../.. && ls -Al / && mv src/* /var/www
      - run: echo "🍏 This job's status is ${{ job.status }}."
