name: Deploy site to Cloudflare Page

on:
  push:
    branches: [main, preview]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository, ${{ GITEA_REF_NAME }} branch has been cloned to the runner."
      - name: Deploy to Local hosting
        run: ls -Al && ls -Al .. && ls -Al .. && mv src/* /data/web/${{ gitea.ref-name }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
